// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVm4Lkktd9yADVhvTiuNanxQbF0vjiP7A',
    appId: '1:972225215464:web:ba4365ec0b6cbb3d95c25d',
    messagingSenderId: '972225215464',
    projectId: 'auth-73005',
    authDomain: 'auth-73005.firebaseapp.com',
    storageBucket: 'auth-73005.appspot.com',
    measurementId: 'G-FWY7GTZ448',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm8VBOnRnfkyeMF5kxB5VDw-ndbO9W98s',
    appId: '1:972225215464:android:cdd92ac3477938e095c25d',
    messagingSenderId: '972225215464',
    projectId: 'auth-73005',
    storageBucket: 'auth-73005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_3F5HpStweTE9rCpKoAPcslnUnB-2SEA',
    appId: '1:972225215464:ios:91c2b86b39ab309395c25d',
    messagingSenderId: '972225215464',
    projectId: 'auth-73005',
    storageBucket: 'auth-73005.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_3F5HpStweTE9rCpKoAPcslnUnB-2SEA',
    appId: '1:972225215464:ios:2b5add734edb1cbd95c25d',
    messagingSenderId: '972225215464',
    projectId: 'auth-73005',
    storageBucket: 'auth-73005.appspot.com',
    iosBundleId: 'com.example.auth.RunnerTests',
  );
}
